### PR TITLE
Added files and functionality

### PR DESCRIPTION
**Pull request by owenshi2**
Added ChatGPT functionality along with voice recognition and TTS output. Refer to requirements.txt for proper libraries.

### CODE REVIEW

**Comment by owenshi2** [comment]
Please check for any bugs/issues then merge if functional

**Comment by SallyXue-0114** [comment]
Hi! Everything looks fine for me! However, I need to homebrew install some packages to make the code run, which took me pretty long to figure out. It could be my personal issue, but if more people encounter these same problems, we could probably notice that in README or something.
1. For TTS, need to install mecab
2. For speech_recognition, need to install flac.

**Comment by owenshi2** [comment]
Got it; do the libraries in the requirement.txt file suffice?

**Comment by SallyXue-0114** [comment]
Yes the libraries in requirement.txt are enough

**Pull request merged**
